/******************************************************************************
 * @file    midi_model.h
 * @author  Andryck Santiago
 * @brief   MIDI Model.
 *
 * @details
 * Defines the data structures used to represent MIDI message types
 * and MIDI messages generated by the application.
 *
 * This model contains only MIDI-related data and does not implement
 * MIDI communication.
 ******************************************************************************/

#ifndef MIDI_MODEL_H
#define MIDI_MODEL_H

/**
 * @brief MIDI message type.
 */
enum class MidiType
{
    ControlChange,
    Note,
    ProgramChange,
};

/**
 * @brief Represents a MIDI message.
 */
struct MidiMessage{
    MidiType type;
    uint8_t channel; // MIDI channel (0-15)
    uint8_t number;  // Control Change number, Note number, or Program Change number
    uint8_t value;   // Value for Control Change or Note velocity, or Program Change
};

#endif // MIDI_MODEL_H